### ISSUE TITLE
Support direct abstraction of code that awaits into functions, without requiring an unnecessary async

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#1482]
### Story

A user should be able to abstract code that awaits into a function, *without* calling that function requiring an extra, expensive message send, i.e. trip through the scheduler and consensus.

### Demo

Consider the current Motoko code:

```
import Mailserver "canister:mailserver";_

actor {
    public func sendAlert() : async Bool {
        let ok1 = 
          if (valid_email("johndoe@mailinator.com")) {
              await Mailserver.send("To: johndoe@mailinator.com\nSubject: A Subject\n\n A Body");
          } else { true };
        let ok2  = if (valid_email("johndoe@mailinator.com")) {
              await Mailserver.send("To: marydoe@mailinator.com\nSubject: B Subject\n\n B Body");
           } else { true };
        return (ok1 and ok2);
    };
```
Clearly, this calls for some refactoring into
```
import Mailserver "canister:mailserver";_

actor {
    public func sendAlert() : async Bool {
        let ok1 : Bool = await sendEmail("johndoe@mailinator.com", "A Subject", "A Body");
        let ok2 : Bool = await sendEmail("marydoe@mailinator.com", "B Subject", "B Body");
        return ok1 and ok2;
    };
    func sendEmail(address : Text, subject: Text, body : Text) : async Bool {
        if (valid_email("johndoe@mailinator.com") { 
          return await Mailserver.send(
                  "To: " # address # "\nSubject: " # subject # "\n\n" # body);
        } else { return true }
    };
};
```
This code abstracts calls to `send` into a function `sendEmail`. Our current compilation scheme causes each call to `sendEmail` to to do one additional message send, increasing latency and the number of context switches.

This is a real example contributed by Dfinity-Alin who rightly asks:
 
> Is this the idiomatic (and most efficient) way to return a promise from a function?
> 
> It looks like the 2 sets of awaits (the one within `sendEmail()` on one hand; and the ones in  `sendAlert()` on the other) result in 2 execution rounds before the canister call is actually made.
> If I instead inline the code of `sendEmail()`, there's only one initial execution round for this canister (followed by an execution round for mailserver; and another execution round for this canister, to handle the response).

A simple demo would show reduced latency of using the old compilation vs new compilation scheme in this example.

The problem is exacerbated by recursion, where each recursive calls to an asynchronous local function induces an additional send.

Consider this recursive evaluator, that calls an asynchronous power function (perhaps provided by a plugin canister in a spreadsheet formula evaluator):

```
import P "mo:prim";
actor a {

  public query func pow(i :Int, n:Int) : async Int {
     power(i, n);
  };

  public type Expression = {
    #const : Int;
    #add : (Expression, Expression);
    #mul : (Expression, Expression);
    #sub : (Expression, Expression);
    #pow : (Expression, Expression);
  };


  func evalAsync(exp : Expression) : async Int {
    switch (exp) {
      case (#const(n)) n;
      case (#add(e1, e2)) (await evalAsync(e1)) + (await evalAsync(e2));
      case (#mul(e1, e2)) (await evalAsync(e1)) * (await evalAsync(e2));
      case (#sub(e1, e2)) (await evalAsync(e1)) - (await evalAsync(e2));
      case (#pow(e1, e2)) await (pow(await (evalAsync e1), await (evalAsync e2)));
    }
  };
};
```
With the current compilation scheme, every call to `evalAsync` in a nested expression causes a context switch, even though only calls to query `pow()` actually require one.

The second demo could use a recursive function such as `evalAsync` to show very dramatic reductions in latency.

### Design

The current proposal is to introduce a new `do async {...}` expression that produces an async value without, on its own, doing a context switch (#2180).

In future, local async functions would desugar to the new `do async {...}` block, instead of context switching `async` blocks.

### Notes

This is just a more realistic example of our inability to abstract await into functions, without doing an unnecessary trip through the scheduler, see #680.

See #1633 for example perf gains in recursive scenarios using a hacked solution.

POC implementation of desing in interpreter, using `do async {}` blocks #2180.

### Progress

As stacked PRs:

- [x] #2180 Implements source typing and AST interpreter. First Draft.
- [x] #2244 Implements high-level ir typing and interpretation. First Draft.
- [x] #2245 Implements lowering to low-level, compilable ir (i.e. await/async transformations). In progress.
- [x] #2277 Implements interpretation of await but not async lowered code, for self-testing

This story is now blocked since Andreas is questioning our semantics of both `await` (longstanding) and `do async` (as proposed here).
