### ISSUE TITLE
Meta-issue: Mercury backlog burndown

### ISSUE THREAD

**Issue by rossberg** [dfinity/motoko#2078]
For Mercury:

- [x] Implement relaxed Candid deserialisation rules (#1959) (yan & joachim)
  * [x] hook up Candid test suite to Motoko (#1830) (yan)
  * [x] update Candid test suite runner to support Candid type definitions (PR #2082)
  * [x] fix UTF-8 handling (joachim, PR #2084)
  * [x] extend Candid test suite to account for relaxed rules (PR dfinity/candid#126)
  * [x] implement backtracking in deserialiser (joachim, PR #2129)
  * [x] allow overlong leb128 sequences (joachim, PR #2085)
  * [x] fix all other issues uncovered by the Candid test suite (joachim, PRs #2122, #2123, #2124, #2125)
- [x] Deprecate Word types (#1824, #2362, #2363) (joachim)
  * [x] add bit operators for NatN and IntN types
  * [x] add wrap-around arithmetic operators for NatN and IntN types
  * [x] produce deprecation warnings for Word types and operators
  * [x] documentation
- [x] Improve record syntax (andreas)
  * [x] non-recursive record literals (#1294) (PR #1876)
  * [x] unambiguous syntax (#1725) (PR #2102)
  * [x] documentation
  * [x] adapt motoko-base
- [x] Introduce option monad (#980) (claudio, PR #2174)
- [x] Finish actor literals and classes (claudio)
  * [x] check sharability of actor class parameters (#1511)
  * [x] async class return type
  * [x] async (closed) actor expressions (#1442) (PR #2116)
  * [ ] local (closed) actor classes
  * [ ] closing over imports
  * [x] documentation

Stretch goals:
- [ ] More efficient async (#680)
- [ ] Consolidate oneway methods (#950)
  * [ ] either disable or introduce new syntax and semantics
- [x] User deprecation annotation?
