### ISSUE TITLE
Meta-issue: Features

### ISSUE THREAD

**Issue by rossberg** [dfinity/motoko#2303]
Small:
- [x] Support checking mode for records (#2240)
- [x] Remove deprecated object/block syntax (#1294)
- [x] Make `actor{}` a subtype of `Principal` (#2264)
- [x] Require type annotations on public class fields (#1290)
- [x] Only allow 'query' short-hand in actor fields, 'shared query' elsewhere (#741)

Medium:
- [x] Remove Word types (#1824, #2362, #2363)
- [x] Directed typing of operators (#853)
- [x] Better error messages for complex type mismatches (#2313)
- [x] Import patterns and type patterns (#2354)
- [ ] `do` monad construct (#4980)
- [ ] Identifier escaping (#1668)
- [x] Operator sections? (#816)
- [x] Type fields in types and records (#760)
- [ ] Consolidate oneway methods (#950)
- [x] Sharable modules (#1452)
- [x] User-defined deprecations (#2361)
- [x] Record merging and field extension (#3072)

Large:
- [x] Cycles and funds (#1981, blocked)
- [ ] Shared generics (#2096, #1655, #1500)
- [x] Expose serialisation primitives (#1183)
- [x] Intersection and union types, mixins (#1841)
- [x] Warn against atomicity bugs? (#792)
- [x] Atomic sections? (#1361)
- [x] Effect system? (#703)
- [x] Define public fields through type annotations? (#2164)
- [x] Canister parameters (Candid/Motoko) (#1827, #2120)
- [x] Stable functions and objects (#707)
- [ ] User-defined custom serialisation? (I.e. `(with serialiser = Json.encode) A.foo(arg)` and `public (with deserialiser = ...) func foo(arg : Int) ...`
