### ISSUE TITLE
Roadmap ideas

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#2556]
Roadmap ideas:

- [ ] language spec
- [ ] higher fidelity repl (cycles, Principal.fromActor, rollback on trap etc)
- [ ] faster await (ideally using scheduler optimization) or some abstraction mechanism for code that awaits
- [ ] canister management beyond canister install 👍🏻 
- [ ] recursive and mutually recursive actor (classes), perhaps using quines and ic0.read_wasm(), or, better, shared wasm on the replicas.
- [ ] FFI 👍🏻 
- [ ] full dfx support for actor classes
- [ ] interface conformance checking (ie. compile against given candid) 👍🏻 
- [ ] Motoko book (short and sweet) 👍🏻 
- [ ] formatting tool
- [ ] multi-canister project support in mo-ide
- [ ] compiler or library support for await-one-of-many
- [ ] join patterns for concurrency control
- [ ] multi-actor transactions
- [ ] GC improvements/large-object heap 👍🏻  
- [ ] Cloneable Text iterators (alternatively, slices)
- [ ] Source code debugging
- [ ] `vessel build`
- [ ] Subtype checking in candid deserialization
- [ ] Generics for Candid 
- [ ] Hosted searchable library documentation (Hoogle/Pursuit)
- [ ] Motoko website (https://www.rust-lang.org/, https://www.purescript.org/, https://www.haskell.org/)
- [ ] More WASI APIs to enable local scripting/testing frameworks (reading stdin, command line parsing, reading/writing files)
- [ ] Text Interpolation/Format strings
- [ ] Local type information in the IDE
- [ ] Dot-completion for records/objects/whatever comes out of #2537 
- [ ] Everything under #2304
